# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97f6cfdf87beca31f45b7f225c6ad7b28ee52cdc8813915da5e1ea642a5def3fbbec698a87fcbf483c5514b64413fee1a52e6efbda6d5a603079fdf98cd2e611

test:
  secret_key_base: ef857f85f6765e91505974266a0ed508e4444a976721700029ed46c2a433324fdec39c81b2576c61ff9ad3ca474234a78daf96180d552924e63a480e276e90da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
